<?php

require dirname(__DIR__, 2) . '/mainfile.php';
include 'language/english/admin.php';
include 'include/bioreg_funcs.php';

add_bio_pop('Adamas', 'formosus', '');
add_bio_pop('Adinia', 'xenica', '');
add_bio_pop('Aphanius', 'anatoliae anatoliae', '');
add_bio_pop('Aphanius', 'anatoliae splendens', '');
add_bio_pop('Aphanius', 'anatoliae sureyanus', '');
add_bio_pop('Aphanius', 'anatoliae transgrediens', '');
add_bio_pop('Aphanius', 'apodus', '');
add_bio_pop('Aphanius', 'asquamatus', '');
add_bio_pop('Aphanius', 'danfordii', '');
add_bio_pop('Aphanius', 'dispar dispar', '');
add_bio_pop('Aphanius', 'dispar richardsoni', '');
add_bio_pop('Aphanius', 'fasciatus', '');
add_bio_pop('Aphanius', 'ginaonis', '');
add_bio_pop('Aphanius', 'iberus', '');
add_bio_pop('Aphanius', 'mento', '');
add_bio_pop('Aphanius', 'sirhani', '');
add_bio_pop('Aphanius', 'sophiae', '');
add_bio_pop('Aphanius', 'vladykovi', '');
add_bio_pop('Aphyolebias', 'obliquus', '');
add_bio_pop('Aphyolebias', 'peruensis', '');
add_bio_pop('Aphyolebias', 'peruensis', 'Santa Anna Nanay');
add_bio_pop('Aphyolebias', 'rubrocaudatus', '');
add_bio_pop('Aphyolebias', 'wischmanni', '');
add_bio_pop('Aphyoplatys', 'duboisi', '');
add_bio_pop('Aphyosemion', 'abacinum', '');
add_bio_pop('Aphyosemion', 'ahli', '');
add_bio_pop('Aphyosemion', 'ahli', 'Bcomo GEML 00-12');
add_bio_pop('Aphyosemion', 'ahli', 'Bicomo GEML 00-15');
add_bio_pop('Aphyosemion', 'ahli', 'Bicomo GEMLB 02-32');
add_bio_pop('Aphyosemion', 'ahli', 'Buabe GEMHS 00-29');
add_bio_pop('Aphyosemion', 'ahli', 'GEMLB 02-26');
add_bio_pop('Aphyosemion', 'ahli', 'Movoho GEMLB 02-29');
add_bio_pop('Aphyosemion', 'ahli', 'Movoho GEMLB 02-31');
add_bio_pop('Aphyosemion', 'ahli', 'Nguba GEMHS 00-36');
add_bio_pop('Aphyosemion', 'ahli', 'Nomenam GEMHS 00-35');
add_bio_pop('Aphyosemion', 'ahli', 'Tica GEMHS 00-28');
add_bio_pop('Aphyosemion', 'alpha', '');
add_bio_pop('Aphyosemion', 'alpha', 'Cap Santa Clara DNA-01');
add_bio_pop('Aphyosemion', 'alpha', 'GJS 00-34 Santa Clara.');
add_bio_pop('Aphyosemion', 'amoenum', '');
add_bio_pop('Aphyosemion', 'aureum', '');
add_bio_pop('Aphyosemion', 'aureum', 'BBW 00-15');
add_bio_pop('Aphyosemion', 'australe', '');
add_bio_pop('Aphyosemion', 'australe', 'Cap Esterias DNA-01');
add_bio_pop('Aphyosemion', 'australe', 'chocolate');
add_bio_pop('Aphyosemion', 'australe', 'GJS 00-31 Cap Esterias');
add_bio_pop('Aphyosemion', 'australe', 'orange');
add_bio_pop('Aphyosemion', 'bamilekorum', '');
add_bio_pop('Aphyosemion', 'batesii', '');
add_bio_pop('Aphyosemion', 'bitaeniatum', '');
add_bio_pop('Aphyosemion', 'bivittatum', '');
add_bio_pop('Aphyosemion', 'bivittatum', 'red TAAG 2000');
add_bio_pop('Aphyosemion', 'boehmi', '');
add_bio_pop('Aphyosemion', 'bualanum', '');
add_bio_pop('Aphyosemion', 'buytaerti', '');
add_bio_pop('Aphyosemion', 'calliurum', '');
add_bio_pop('Aphyosemion', 'cameronense', '');
add_bio_pop('Aphyosemion', 'cameronense', 'Acoesi (Rio Abea) GEMHS 00-15');
add_bio_pop('Aphyosemion', 'cameronense', 'Aconibe GEMLB 02-11');
add_bio_pop('Aphyosemion', 'cameronense', 'Andenbe GEMHS 00-03');
add_bio_pop('Aphyosemion', 'cameronense', 'Anugon GEM 02-16');
add_bio_pop('Aphyosemion', 'cameronense', 'Bidodo GEMLB 02-25');
add_bio_pop('Aphyosemion', 'cameronense', 'Ebibeyin GEMLB 02-23');
add_bio_pop('Aphyosemion', 'cameronense', 'GEMHS 00-04');
add_bio_pop('Aphyosemion', 'cameronense', 'GEMLB 02-12');
add_bio_pop('Aphyosemion', 'cameronense', 'GEMLB 02-13');
add_bio_pop('Aphyosemion', 'cameronense', 'GEMLB 02-14');
add_bio_pop('Aphyosemion', 'cameronense', 'GEMLB 02-15');
add_bio_pop('Aphyosemion', 'cameronense', 'haasi ACH1 DNA-02');
add_bio_pop('Aphyosemion', 'cameronense', 'haasi ACH2 DNA');
add_bio_pop('Aphyosemion', 'cameronense', 'halleri G EMLB 02-23');
add_bio_pop('Aphyosemion', 'cameronense', 'halleri Misa GEMHS 00-22');
add_bio_pop('Aphyosemion', 'cameronense', 'Iasang GEM 00-23');
add_bio_pop('Aphyosemion', 'cameronense', 'Melang GEMHS 00-21');
add_bio_pop('Aphyosemion', 'cameronense', 'Miboman GEMLB 02-21');
add_bio_pop('Aphyosemion', 'cameronense', 'Mikien GEMLB 02-24');
add_bio_pop('Aphyosemion', 'cameronense', 'Mimboman GEMLB 02-17');
add_bio_pop('Aphyosemion', 'cameronense', 'Morlota GEMHS 00-02');
add_bio_pop('Aphyosemion', 'cameronense', 'Ngosoc GEMHS 00-19');
add_bio_pop('Aphyosemion', 'cameronense', 'Niefang GEMHS 00-01');
add_bio_pop('Aphyosemion', 'cameronense', 'Nsoc 1 GEMHS 00-16');
add_bio_pop('Aphyosemion', 'cameronense', 'Nsoc 2 GEMHS 00-17');
add_bio_pop('Aphyosemion', 'cameronense', 'Rio Monto GEMHS 00-18');
add_bio_pop('Aphyosemion', 'cameronense', 'Sam DNA-01');
add_bio_pop('Aphyosemion', 'caudofasciatum', '');
add_bio_pop('Aphyosemion', 'celiae celiae', '');
add_bio_pop('Aphyosemion', 'celiae winifredae', '');
add_bio_pop('Aphyosemion', 'chauchei', '');
add_bio_pop('Aphyosemion', 'christyi', '');
add_bio_pop('Aphyosemion', 'christyi', 'CIM-01');
add_bio_pop('Aphyosemion', 'cintrineipinnis', '');
add_bio_pop('Aphyosemion', 'cintrineipinnis', 'BBW 00-4');
add_bio_pop('Aphyosemion', 'cintrineipinnis', 'BBW 00-5');
add_bio_pop('Aphyosemion', 'cintrineipinnis', 'BBW 00-6');
add_bio_pop('Aphyosemion', 'cintrineipinnis', 'BBW 00-7');
add_bio_pop('Aphyosemion', 'citrineipinnis', '');
add_bio_pop('Aphyosemion', 'citrineipinnis', 'GJS 00-3 Massika');
add_bio_pop('Aphyosemion', 'coeleste', '');
add_bio_pop('Aphyosemion', 'cognatum', '');
add_bio_pop('Aphyosemion', 'cognatum', 'TAAG 2000-1');
add_bio_pop('Aphyosemion', 'congicum', '');
add_bio_pop('Aphyosemion', 'cyanostictum', '');
add_bio_pop('Aphyosemion', 'dargei', '');
add_bio_pop('Aphyosemion', 'decorsei', '');
add_bio_pop('Aphyosemion', 'edeanum', '');
add_bio_pop('Aphyosemion', 'elberti', 'N\\\'tui');
add_bio_pop('Aphyosemion', 'elberti', 'Nganga Eboko');
add_bio_pop('Aphyosemion', 'elegans', '');
add_bio_pop('Aphyosemion', 'exigoideum', '');
add_bio_pop('Aphyosemion', 'exigoideum', 'BBW 00-2');
add_bio_pop('Aphyosemion', 'exigoideum', 'BBW 00-3');
add_bio_pop('Aphyosemion', 'exiguum', '');
add_bio_pop('Aphyosemion', 'ferranti', '');
add_bio_pop('Aphyosemion', 'franzwerneri', '');
add_bio_pop('Aphyosemion', 'fulgens', '');
add_bio_pop('Aphyosemion', 'gabunense', '');
add_bio_pop('Aphyosemion', 'gabunense gabunense', 'GBG 93/30');
add_bio_pop('Aphyosemion', 'georgiae', '');
add_bio_pop('Aphyosemion', 'georgiae', 'LEC 93/2');
add_bio_pop('Aphyosemion', 'haasi', '');
add_bio_pop('Aphyosemion', 'halleri', '');
add_bio_pop('Aphyosemion', 'hanneloreae hanneloreae', '');
add_bio_pop('Aphyosemion', 'hanneloreae wuendschi', '');
add_bio_pop('Aphyosemion', 'heinemanni', '');
add_bio_pop('Aphyosemion', 'hera', '');
add_bio_pop('Aphyosemion', 'hera', '1-2 ARK/96');
add_bio_pop('Aphyosemion', 'hera', 'GJS 00-28 Bengui 3');
add_bio_pop('Aphyosemion', 'hera', 'GJS 00-29 Bengui 1-2');
add_bio_pop('Aphyosemion', 'herzogi', '');
add_bio_pop('Aphyosemion', 'herzogi', 'Acoesi (Rio Abea)');
add_bio_pop('Aphyosemion', 'herzogi', 'Akok GEMHS 00-07');
add_bio_pop('Aphyosemion', 'herzogi', 'Akorenam GEMHS 00-09');
add_bio_pop('Aphyosemion', 'herzogi', 'Akork GEML 00-06');
add_bio_pop('Aphyosemion', 'herzogi', 'Bandili GEMLB 02-07');
add_bio_pop('Aphyosemion', 'herzogi', 'Bidodo GEM 02-25');
add_bio_pop('Aphyosemion', 'herzogi', 'Bisum GEMLB 02-03');
add_bio_pop('Aphyosemion', 'herzogi', 'GEMLB 02-15');
add_bio_pop('Aphyosemion', 'herzogi', 'Mbam GEMHS 00-12');
add_bio_pop('Aphyosemion', 'herzogi', 'Mbam GEMLB 02-09');
add_bio_pop('Aphyosemion', 'herzogi', 'Miboman GEMLB 02-21');
add_bio_pop('Aphyosemion', 'herzogi', 'Mikien GEMLB 02-24');
add_bio_pop('Aphyosemion', 'herzogi', 'Nsoc 1 GEMHS 00-16');
add_bio_pop('Aphyosemion', 'herzogi', 'Nsoc 2 GEMHS 00-17');
add_bio_pop('Aphyosemion', 'herzogi', 'Okung GEMLB 02-08');
add_bio_pop('Aphyosemion', 'herzogi', 'Otong-Alam GEML 00-08');
add_bio_pop('Aphyosemion', 'herzogi', 'Oveng GEML 00-09');
add_bio_pop('Aphyosemion', 'herzogi', 'Rio Monto GEMHS 00-18');
add_bio_pop('Aphyosemion', 'herzogi', 'Soha GEML 00-07');
add_bio_pop('Aphyosemion', 'herzogi', 'Soha GEMLB 02-04');
add_bio_pop('Aphyosemion', 'herzogi', 'Yama GEMHS 00-10');
add_bio_pop('Aphyosemion', 'herzogi', 'Yama GEML 00-05');
add_bio_pop('Aphyosemion', 'hofmanni', '');
add_bio_pop('Aphyosemion', 'hofmanni', 'BBW 00-20');
add_bio_pop('Aphyosemion', 'hofmanni', 'GJS 00-6 Myanga');
add_bio_pop('Aphyosemion', 'joergenscheeli', '');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'BBW 00-17');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'BBW 00-19');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'BBW 00-21');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'BBW 00-9');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'GJS 00-13 Nguambanga');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'GJS 00-5 Sika-Sika');
add_bio_pop('Aphyosemion', 'joergenscheeli', 'GJS 00-8 Takamogikou');
add_bio_pop('Aphyosemion', 'kekemense', '');
add_bio_pop('Aphyosemion', 'kouamense', '');
add_bio_pop('Aphyosemion', 'labarrei', '');
add_bio_pop('Aphyosemion', 'lamberti', '');
add_bio_pop('Aphyosemion', 'lefiniense', '');
add_bio_pop('Aphyosemion', 'loennbergii', '');
add_bio_pop('Aphyosemion', 'louessense', '');
add_bio_pop('Aphyosemion', 'lugens', '');
add_bio_pop('Aphyosemion', 'lujae', '');
add_bio_pop('Aphyosemion', 'maculatum', '');
add_bio_pop('Aphyosemion', 'maculatum', 'Lolo 1 DNA-01');
add_bio_pop('Aphyosemion', 'marginatum', '');
add_bio_pop('Aphyosemion', 'marginatum', 'GJS 00-29 Bengui 1-2');
add_bio_pop('Aphyosemion', 'microphtalmum', '');
add_bio_pop('Aphyosemion', 'microphtalmum', 'BBW 00-25');
add_bio_pop('Aphyosemion', 'mimbon', '');
add_bio_pop('Aphyosemion', 'mimbon', 'Acurenam GEMLB 02-06');
add_bio_pop('Aphyosemion', 'mimbon', 'Acurenan GEML 00-10');
add_bio_pop('Aphyosemion', 'mimbon', 'Akok GEMHS 00-07');
add_bio_pop('Aphyosemion', 'mimbon', 'Akorenam GEMHS 00-09');
add_bio_pop('Aphyosemion', 'mimbon', 'Ayene GEMLB 02-03');
add_bio_pop('Aphyosemion', 'mimbon', 'Bandili GEMLB 02-07');
add_bio_pop('Aphyosemion', 'mimbon', 'GEMLB 02-10');
add_bio_pop('Aphyosemion', 'mimbon', 'Mbam GEMLB 03-09');
add_bio_pop('Aphyosemion', 'mimbon', 'Melan GEMHS 00-11');
add_bio_pop('Aphyosemion', 'mimbon', 'Nkinner DNA');
add_bio_pop('Aphyosemion', 'mimbon', 'Okung GEMLB 02-08');
add_bio_pop('Aphyosemion', 'mimbon', 'Otong-Alam, GEML 00-08');
add_bio_pop('Aphyosemion', 'mimbon', 'Oveng GEML 00-09');
add_bio_pop('Aphyosemion', 'mimbon', 'San Carlos GEMHS 00-08');
add_bio_pop('Aphyosemion', 'mimbon', 'San Carlos GEMLB 02-05');
add_bio_pop('Aphyosemion', 'mimbon', 'Soha GEML 00-07');
add_bio_pop('Aphyosemion', 'mimbon', 'Soha GEMLB 02-04');
add_bio_pop('Aphyosemion', 'mimbon', 'Yama GEMHS 00-10');
add_bio_pop('Aphyosemion', 'mimbon', 'Yama GEML 0-05');
add_bio_pop('Aphyosemion', 'obscurum', '');
add_bio_pop('Aphyosemion', 'ocellatum', '');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-10');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-11');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-17');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-18');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-19');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-21');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-8');
add_bio_pop('Aphyosemion', 'ocellatum', 'BBW 00-9');
add_bio_pop('Aphyosemion', 'ocellatum', 'GJS 00-5 Sika-Sika');
add_bio_pop('Aphyosemion', 'ogoense', '');
add_bio_pop('Aphyosemion', 'ottogartneri', '');
add_bio_pop('Aphyosemion', 'pascheni festivum', '');
add_bio_pop('Aphyosemion', 'pascheni pascheni', '');
add_bio_pop('Aphyosemion', 'passaroi', '');
add_bio_pop('Aphyosemion', 'passaroi', 'BBW 00-14');
add_bio_pop('Aphyosemion', 'passaroi', 'BBW 00-15');
add_bio_pop('Aphyosemion', 'poliaki', '');
add_bio_pop('Aphyosemion', 'polli', '');
add_bio_pop('Aphyosemion', 'primigenium', '');
add_bio_pop('Aphyosemion', 'primigenium', 'BBW 00-23');
add_bio_pop('Aphyosemion', 'punctatum', '');
add_bio_pop('Aphyosemion', 'pyrophore', '');
add_bio_pop('Aphyosemion', 'raddai', '');
add_bio_pop('Aphyosemion', 'rectogoense', '');
add_bio_pop('Aphyosemion', 'riggenbachi', '');
add_bio_pop('Aphyosemion', 'schioetzi', '');
add_bio_pop('Aphyosemion', 'schluppi', '');
add_bio_pop('Aphyosemion', 'seegersi', '');
add_bio_pop('Aphyosemion', 'sp.', '');
add_bio_pop('Aphyosemion', 'sp.', 'aff. cameronense Rio Malono GEMHS 00-14');
add_bio_pop('Aphyosemion', 'sp.', 'aff. cameronense Rio Nkeme GEMHS 00-13');
add_bio_pop('Aphyosemion', 'sp.', 'aff. citrineipinnis BBW 00-12');
add_bio_pop('Aphyosemion', 'sp.', 'aff. citrineipinnis BBW 00-13');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Binogo GEML 00-2');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Bisun GEMHS 00-05');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Fang GEML 00-01');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Ndyengayong GEMHS 00-06');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Oteon-Asoc GEML 00-03');
add_bio_pop('Aphyosemion', 'sp.', 'aff. maculatum Rio Aseng GEMLB 02-02');
add_bio_pop('Aphyosemion', 'sp.', 'aff. mimbon Mbam GEMHS 00-12,');
add_bio_pop('Aphyosemion', 'sp.', 'aff. primigenium GJS 00-26 Bandi');
add_bio_pop('Aphyosemion', 'sp.', 'BBW 00-1');
add_bio_pop('Aphyosemion', 'splendidum', '');
add_bio_pop('Aphyosemion', 'splendopleure', '');
add_bio_pop('Aphyosemion', 'splendopleure', 'Ndog Bong, CBL 2001/10');
add_bio_pop('Aphyosemion', 'striatum', '');
add_bio_pop('Aphyosemion', 'striatum', 'Abengnam GEMHS 00-34');
add_bio_pop('Aphyosemion', 'striatum', 'BBW 00-25');
add_bio_pop('Aphyosemion', 'striatum', 'BBW 00-26');
add_bio_pop('Aphyosemion', 'striatum', 'BBW 00-27');
add_bio_pop('Aphyosemion', 'striatum', 'GEMHS 00-33');
add_bio_pop('Aphyosemion', 'striatum', 'GJS 00-28 Bengui 3');
add_bio_pop('Aphyosemion', 'striatum', 'Lambarene');
add_bio_pop('Aphyosemion', 'thysi', '');
add_bio_pop('Aphyosemion', 'tirbaki', '');
add_bio_pop('Aphyosemion', 'volcanum', '');
add_bio_pop('Aphyosemion', 'wachtersi', '');
add_bio_pop('Aphyosemion', 'wildekampi', '');
add_bio_pop('Aphyosemion', 'zygaima', '');
add_bio_pop('Aplocheilichthy', 'bukobanus', '');
add_bio_pop('Aplocheilichthy', 'bukobanus', 'Tarime River TAN 00-3');
add_bio_pop('Aplocheilichthys', 'sp.', '');
add_bio_pop('Aplocheilichthys', 'sp.', 'Ebibeyin GEMLB 02-23');
add_bio_pop('Aplocheilichthys', 'sp.', 'TZL 48-01.');
add_bio_pop('Aplocheilichthys', 'spilauchen', '');
add_bio_pop('Aplocheilichthys', 'spilauchen', 'Rio Ue GEMLB 02-28');
add_bio_pop('Aplocheilichthys', 'spilauchen', 'Utonde GEMLB 02-27');
add_bio_pop('Aplocheilus', 'blockii', '');
add_bio_pop('Aplocheilus', 'dayi dayi', '');
add_bio_pop('Aplocheilus', 'dayi werneri', '');
add_bio_pop('Aplocheilus', 'kirchmayeri', '');
add_bio_pop('Aplocheilus', 'lineatus', '');
add_bio_pop('Aplocheilus', 'panchax', '');
add_bio_pop('Aplocheilus', 'panchax', 'KW 01-14');
add_bio_pop('Aplocheilus', 'panchax panchax', '');
add_bio_pop('Aplocheilus', 'panchax siamensis', '');
add_bio_pop('Aplocheilus', 'parvus', '');
add_bio_pop('Archiaphyosemion', 'guineense', '');
add_bio_pop('Archiaphyosemion', 'jeanpoli', '');
add_bio_pop('Archiaphyosemion', 'maeseni', '');
add_bio_pop('Archiaphyosemion', 'petersi', '');
add_bio_pop('Archiaphyosemion', 'viride', '');
add_bio_pop('Austrofundulus', 'limnaeus', '');
add_bio_pop('Austrofundulus', 'limnaeus', 'Bachaquero BBL 01-02');
add_bio_pop('Austrofundulus', 'transilis', '');
add_bio_pop('Austrofundulus', 'transilis', 'Apure BBL 01-05');
add_bio_pop('Austrofundulus', 'transilis', 'Finca BBL 01-06');
add_bio_pop('Austrofundulus', 'transilis', 'PapelóBL 01-03');
add_bio_pop('Austrolebias', 'adloffi', '');
add_bio_pop('Austrolebias', 'affinis', '');
add_bio_pop('Austrolebias', 'alexandri', '');
add_bio_pop('Austrolebias', 'bellottii', '');
add_bio_pop('Austrolebias', 'bellottii', 'Ezeiza');
add_bio_pop('Austrolebias', 'carvalhoi', '');
add_bio_pop('Austrolebias', 'cinereus', '');
add_bio_pop('Austrolebias', 'gymnoventris', '');
add_bio_pop('Austrolebias', 'ibicuiensis', '');
add_bio_pop('Austrolebias', 'luteoflammulatus', '');
add_bio_pop('Austrolebias', 'melanoorus', '');
add_bio_pop('Austrolebias', 'nigripinnis', '');
add_bio_pop('Austrolebias', 'nigripinnis', 'Camelo');
add_bio_pop('Austrolebias', 'nigripinnis', 'Villa Soriano');
add_bio_pop('Austrolebias', 'nioni', '');
add_bio_pop('Austrolebias', 'nonoiuliensis', '');
add_bio_pop('Austrolebias', 'patriciae', '');
add_bio_pop('Austrolebias', 'sp.', '');
add_bio_pop('Austrolebias', 'vandenbergi', '');
add_bio_pop('Austrolebias', 'vazferreirai', '');
add_bio_pop('Austrolebias', 'viarius', '');
add_bio_pop('Callopanchax', 'monroviae', '');
add_bio_pop('Callopanchax', 'occidentalis', '');
add_bio_pop('Callopanchax', 'toddi', '');
add_bio_pop('Campellolebias', 'brucei', '');
add_bio_pop('Campellolebias', 'chrysolineatus', '');
add_bio_pop('Campellolebias', 'dorsimaculatus', '');
add_bio_pop('Campellolebias', 'dorsimaculatus', 'Barra do Ribeira RDB 01-01');
add_bio_pop('Chriopeoides', 'pengelleyi', '');
add_bio_pop('Chromaphyosemion', 'sp.', '');
add_bio_pop('Chromaphyosemion', 'sp.', 'Abengnam GEMHS 00-34');
add_bio_pop('Chromaphyosemion', 'sp.', 'Ayakue GEML 00-13');
add_bio_pop('Chromaphyosemion', 'sp.', 'Bata GEMHS 00-26');
add_bio_pop('Chromaphyosemion', 'sp.', 'Bicomo GEML 00-15');
add_bio_pop('Chromaphyosemion', 'sp.', 'Bicomo GEMLB 02-32');
add_bio_pop('Chromaphyosemion', 'sp.', 'Bioko GEMHS 00-43');
add_bio_pop('Chromaphyosemion', 'sp.', 'Bioko GEMHS 00-44');
add_bio_pop('Chromaphyosemion', 'sp.', 'Buabe GEMHS 00-29');
add_bio_pop('Chromaphyosemion', 'sp.', 'GEMLB 02-26');
add_bio_pop('Chromaphyosemion', 'sp.', 'Liengue GEMHS 00-30');
add_bio_pop('Chromaphyosemion', 'sp.', 'Ncomedyi GEMHS 00-25');
add_bio_pop('Chromaphyosemion', 'sp.', 'Nguba GEMHS 00-36');
add_bio_pop('Chromaphyosemion', 'sp.', 'Nlosoc GEMHS 00-31');
add_bio_pop('Chromaphyosemion', 'sp.', 'Nsupu GEMHS 00-42');
add_bio_pop('Chromaphyosemion', 'sp.', 'Tica GEMHS 00-28');
add_bio_pop('Crenichthys', 'baileyi albivallis', '');
add_bio_pop('Crenichthys', 'baileyi baileyi', '');
add_bio_pop('Crenichthys', 'baileyi grandis', '');
add_bio_pop('Crenichthys', 'baileyi moapae', '');
add_bio_pop('Crenichthys', 'baileyi thermophilus', '');
add_bio_pop('Crenichthys', 'nevadae', '');
add_bio_pop('Cualac', 'tessellatus', '');
add_bio_pop('Cubanichthys', 'cubensis', '');
add_bio_pop('Cynolebias', 'albipunctatus', '');
add_bio_pop('Cynolebias', 'gilbertoi', '');
add_bio_pop('Cynolebias', 'griseus', '');
add_bio_pop('Cynolebias', 'leptocephalus', '');
add_bio_pop('Cynolebias', 'microphthalmus', '');
add_bio_pop('Cynolebias', 'perforatus', '');
add_bio_pop('Cynolebias', 'porosus', '');
add_bio_pop('Cynopoecilus', 'melanotaenia', '');
add_bio_pop('Cyprinodon', 'alvarezi', '');
add_bio_pop('Cyprinodon', 'atrorus', '');
add_bio_pop('Cyprinodon', 'beltrani', '');
add_bio_pop('Cyprinodon', 'bifasciatus', '');
add_bio_pop('Cyprinodon', 'bobmilleri', '');
add_bio_pop('Cyprinodon', 'bondi', '');
add_bio_pop('Cyprinodon', 'bovinus', '');
add_bio_pop('Cyprinodon', 'ceciliae', '');
add_bio_pop('Cyprinodon', 'dearborni', '');
add_bio_pop('Cyprinodon', 'diabolis', '');
add_bio_pop('Cyprinodon', 'elegans', '');
add_bio_pop('Cyprinodon', 'eximius', '');
add_bio_pop('Cyprinodon', 'fontinalis', '');
add_bio_pop('Cyprinodon', 'higuey', '');
add_bio_pop('Cyprinodon', 'immemoriam', '');
add_bio_pop('Cyprinodon', 'labiosus', '');
add_bio_pop('Cyprinodon', 'laciniatus', '');
add_bio_pop('Cyprinodon', 'latifasciatus', '');
add_bio_pop('Cyprinodon', 'longidorsalis', '');
add_bio_pop('Cyprinodon', 'macrolepis', '');
add_bio_pop('Cyprinodon', 'macularius californiensis', '');
add_bio_pop('Cyprinodon', 'macularius eremus', '');
add_bio_pop('Cyprinodon', 'macularius macularius', '');
add_bio_pop('Cyprinodon', 'maya', '');
add_bio_pop('Cyprinodon', 'meeki', '');
add_bio_pop('Cyprinodon', 'nevadensis amargosae', '');
add_bio_pop('Cyprinodon', 'nevadensis calidae', '');
add_bio_pop('Cyprinodon', 'nevadensis nevadensis', '');
add_bio_pop('Cyprinodon', 'nevadensis pectoralis', '');
add_bio_pop('Cyprinodon', 'nevadensis shoshone', '');
add_bio_pop('Cyprinodon', 'nichollsi', '');
add_bio_pop('Cyprinodon', 'pachycephalus', '');
add_bio_pop('Cyprinodon', 'pecosensis', '');
add_bio_pop('Cyprinodon', 'radiosus', '');
add_bio_pop('Cyprinodon', 'rubrofluviatilis', '');
add_bio_pop('Cyprinodon', 'salinus milleri', '');
add_bio_pop('Cyprinodon', 'salinus salinus', '');
add_bio_pop('Cyprinodon', 'simus', '');
add_bio_pop('Cyprinodon', 'simus', 'GUAPP 1-2001 Chiminos, Rio Petexbatum');
add_bio_pop('Cyprinodon', 'tularosa', '');
add_bio_pop('Cyprinodon', 'variegatus artifrons', '');
add_bio_pop('Cyprinodon', 'variegatus baconi', '');
add_bio_pop('Cyprinodon', 'variegatus hubbsi', '');
add_bio_pop('Cyprinodon', 'variegatus ovinus', '');
add_bio_pop('Cyprinodon', 'variegatus riverendi', '');
add_bio_pop('Cyprinodon', 'variegatus variegatus', '');
add_bio_pop('Cyprinodon', 'verecundus', '');
add_bio_pop('Cyprinodon', 'veronicae', '');
add_bio_pop('Diapteron', 'abacinum', '');
add_bio_pop('Diapteron', 'cyanostictum', '');
add_bio_pop('Diapteron', 'cyanostictum', 'Nsoc 1 GEMHS 00-16');
add_bio_pop('Diapteron', 'fulgens', '');
add_bio_pop('Diapteron', 'georgiae', '');
add_bio_pop('Diapteron', 'seegersi', '');
add_bio_pop('Empetrichthys', 'latos concavus', '');
add_bio_pop('Empetrichthys', 'latos latos', '');
add_bio_pop('Empetrichthys', 'latos pahrump', '');
add_bio_pop('Empetrichthys', 'merriami', '');
add_bio_pop('Epiplatys', 'annulatus', '');
add_bio_pop('Epiplatys', 'ansorgii', '');
add_bio_pop('Epiplatys', 'ansorgii', 'GJS 00-2');
add_bio_pop('Epiplatys', 'barmoiensis', '');
add_bio_pop('Epiplatys', 'biafranus', '');
add_bio_pop('Epiplatys', 'bifasciatus bifasciatus', '');
add_bio_pop('Epiplatys', 'bifasciatus taeniatus', '');
add_bio_pop('Epiplatys', 'boulengeri', '');
add_bio_pop('Epiplatys', 'chaperi chaperi', '');
add_bio_pop('Epiplatys', 'chaperi schreiberi', '');
add_bio_pop('Epiplatys', 'chaperi sheljuzhkoi', '');
add_bio_pop('Epiplatys', 'chaperi spillmanni', '');
add_bio_pop('Epiplatys', 'chevalieri', '');
add_bio_pop('Epiplatys', 'coccinatus', '');
add_bio_pop('Epiplatys', 'dageti dageti', '');
add_bio_pop('Epiplatys', 'dageti monroviae', '');
add_bio_pop('Epiplatys', 'esekanus', '');
add_bio_pop('Epiplatys', 'etzeli', '');
add_bio_pop('Epiplatys', 'fasciolatus fasciolatus', '');
add_bio_pop('Epiplatys', 'fasciolatus josianae', '');
add_bio_pop('Epiplatys', 'fasciolatus tototaensis', '');
add_bio_pop('Epiplatys', 'fasciolatus zimiensis', '');
add_bio_pop('Epiplatys', 'grahami', '');
add_bio_pop('Epiplatys', 'grahami', 'GEMLB 02-30');
add_bio_pop('Epiplatys', 'grahami', 'Movoho GEMLB 02-29');
add_bio_pop('Epiplatys', 'guineensis', '');
add_bio_pop('Epiplatys', 'hildegardae', '');
add_bio_pop('Epiplatys', 'huberi', '');
add_bio_pop('Epiplatys', 'huberi', 'BBW 00-2');
add_bio_pop('Epiplatys', 'huberi', 'BBW 00-3');
add_bio_pop('Epiplatys', 'huberi', 'GJS 00-22 Douengui,');
add_bio_pop('Epiplatys', 'huberi', 'GJS 0026 Bandi');
add_bio_pop('Epiplatys', 'infrafasciatus', '');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Bata GEMHS 00-26');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Bioko GEMHS 00-43');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Bioko GEMHS 00-44');
add_bio_pop('Epiplatys', 'infrafasciatus', 'GEMLB 02-26');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Ncomedyi GEMHS 00-25');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Nguba GEMHS 00-36');
add_bio_pop('Epiplatys', 'infrafasciatus', 'Nsupu GEMHS 00-42');
add_bio_pop('Epiplatys', 'infrafasciatus baroi', '');
add_bio_pop('Epiplatys', 'infrafasciatus infrafasciatus', '');
add_bio_pop('Epiplatys', 'infrasciatus rathkei', '');
add_bio_pop('Epiplatys', 'lamottei', '');
add_bio_pop('Epiplatys', 'longiventralis', '');
add_bio_pop('Epiplatys', 'mesogramma', '');
add_bio_pop('Epiplatys', 'multifasciatus', '');
add_bio_pop('Epiplatys', 'neumanni', '');
add_bio_pop('Epiplatys', 'njalaensis', '');
add_bio_pop('Epiplatys', 'olbrechtsi azureus', '');
add_bio_pop('Epiplatys', 'olbrechtsi dauresi', '');
add_bio_pop('Epiplatys', 'olbrechtsi kassiapleuensis', '');
add_bio_pop('Epiplatys', 'olbrechtsi olbrechtsi', '');
add_bio_pop('Epiplatys', 'olbrechtsi puetzi', '');
add_bio_pop('Epiplatys', 'phoeniceps', '');
add_bio_pop('Epiplatys', 'roloffi', '');
add_bio_pop('Epiplatys', 'ruhkopfi', '');
add_bio_pop('Epiplatys', 'sangmelinensis', '');
add_bio_pop('Epiplatys', 'sexfasciatus', '');
add_bio_pop('Epiplatys', 'sexfasciatus', 'BBW 00-1');
add_bio_pop('Epiplatys', 'sexfasciatus', 'BBW 00-25');
add_bio_pop('Epiplatys', 'sexfasciatus', 'Bicomo GEMLB 02-32');
add_bio_pop('Epiplatys', 'singa', '');
add_bio_pop('Epiplatys', 'singa', 'BBW 00-24');
add_bio_pop('Epiplatys', 'singa', 'GJS 00-33 Cap Esterias');
add_bio_pop('Epiplatys', 'sp.', '');
add_bio_pop('Epiplatys', 'sp.', 'Bcomo GEML 00-12');
add_bio_pop('Epiplatys', 'sp.', 'Bicomo GEML 00-15');
add_bio_pop('Epiplatys', 'sp.', 'Movo GEML 00-14');
add_bio_pop('Epiplatys', 'sp.', 'Negba Nguba II GEML 00-16');
add_bio_pop('Epiplatys', 'sp.', 'Sindara BBW 00-1');
add_bio_pop('Epiplatys', 'sp.', 'Wuba I GEML 00-11');
add_bio_pop('Epiplatys', 'spilargyreius', '');
add_bio_pop('Epiplatys', 'togolensis', '');
add_bio_pop('Episemion', 'callipteron', '');
add_bio_pop('Episemion', 'callipteron', 'Acurenan GEML 00-10');
add_bio_pop('Episemion', 'callipteron', 'GEMLB 02-15');
add_bio_pop('Episemion', 'callipteron', 'Soha GEML 00-07');
add_bio_pop('Episemion', 'callipteron', 'Soha GEMLB 02-04');
add_bio_pop('Floridichthys', 'carpio', '');
add_bio_pop('Floridichthys', 'polyommus', '');
add_bio_pop('Fluviphylax', 'obscurum', '');
add_bio_pop('Fluviphylax', 'pygmaeus', '');
add_bio_pop('Fluviphylax', 'simplex', '');
add_bio_pop('Fluviphylax', 'zonatus', '');
add_bio_pop('Foerschichthys', 'nigeriensis', '');
add_bio_pop('Fundulopanchax', 'amieti', '');
add_bio_pop('Fundulopanchax', 'arnoldi', '');
add_bio_pop('Fundulopanchax', 'arnoldi', 'Ughelli TR01');
add_bio_pop('Fundulopanchax', 'avichang', '');
add_bio_pop('Fundulopanchax', 'avichang', 'Negba Nguba II GEML 00-16');
add_bio_pop('Fundulopanchax', 'batesii', '');
add_bio_pop('Fundulopanchax', 'batesii', 'GEMLB 02-18');
add_bio_pop('Fundulopanchax', 'batesii', 'Iasang GEMHS 00-24');
add_bio_pop('Fundulopanchax', 'batesii', 'MelangGEMHS 00-21');
add_bio_pop('Fundulopanchax', 'cinnamomeus', '');
add_bio_pop('Fundulopanchax', 'deltaensis', '');
add_bio_pop('Fundulopanchax', 'filamentosus', '');
add_bio_pop('Fundulopanchax', 'gardneri clauseni', '');
add_bio_pop('Fundulopanchax', 'gardneri gardneri', '');
add_bio_pop('Fundulopanchax', 'gardneri gardneri', 'Albino');
add_bio_pop('Fundulopanchax', 'gardneri gardneri', 'Misaje');
add_bio_pop('Fundulopanchax', 'gardneri gardneri', 'N\\\'sukka');
add_bio_pop('Fundulopanchax', 'gardneri lacustris', '');
add_bio_pop('Fundulopanchax', 'gardneri mamfensis', '');
add_bio_pop('Fundulopanchax', 'gularis', '');
add_bio_pop('Fundulopanchax', 'kribianus', '');
add_bio_pop('Fundulopanchax', 'marmoratus', '');
add_bio_pop('Fundulopanchax', 'mirabilis intermittens', '');
add_bio_pop('Fundulopanchax', 'mirabilis mirabilis', '');
add_bio_pop('Fundulopanchax', 'mirabilis moensis', '');
add_bio_pop('Fundulopanchax', 'mirabilis traudeae', '');
add_bio_pop('Fundulopanchax', 'ndianus', '');
add_bio_pop('Fundulopanchax', 'nigerianus', '');
add_bio_pop('Fundulopanchax', 'oeseri', '');
add_bio_pop('Fundulopanchax', 'oeseri', 'Rio Barabaabo GEMHS 00-44.');
add_bio_pop('Fundulopanchax', 'powelli', '');
add_bio_pop('Fundulopanchax', 'puerzli', '');
add_bio_pop('Fundulopanchax', 'robertsoni', '');
add_bio_pop('Fundulopanchax', 'rubrolabialis', '');
add_bio_pop('Fundulopanchax', 'scheeli', '');
add_bio_pop('Fundulopanchax', 'schwoiseri', '');
add_bio_pop('Fundulopanchax', 'sjoestedti', '');
add_bio_pop('Fundulopanchax', 'spoorenbergi', '');
add_bio_pop('Fundulopanchax', 'walkeri', '');
add_bio_pop('Fundulosoma', 'thierryi', '');
add_bio_pop('Fundulus', 'albolineatus', '');
add_bio_pop('Fundulus', 'auroguttatus', '');
add_bio_pop('Fundulus', 'bermudae', '');
add_bio_pop('Fundulus', 'bifax', '');
add_bio_pop('Fundulus', 'blairae', '');
add_bio_pop('Fundulus', 'catenatus', '');
add_bio_pop('Fundulus', 'chrysotus', '');
add_bio_pop('Fundulus', 'cingulatus', '');
add_bio_pop('Fundulus', 'confluentus', '');
add_bio_pop('Fundulus', 'diaphanus diaphanus', '');
add_bio_pop('Fundulus', 'diaphanus menona', '');
add_bio_pop('Fundulus', 'dispar', '');
add_bio_pop('Fundulus', 'escambiae', '');
add_bio_pop('Fundulus', 'euryzonus', '');
add_bio_pop('Fundulus', 'grandis grandis', '');
add_bio_pop('Fundulus', 'grandis saguanus', '');
add_bio_pop('Fundulus', 'grandissimus', '');
add_bio_pop('Fundulus', 'heteroclitus heteroclitus', '');
add_bio_pop('Fundulus', 'heteroclitus macrolepidotus', '');
add_bio_pop('Fundulus', 'jenkinsi', '');
add_bio_pop('Fundulus', 'julisia', '');
add_bio_pop('Fundulus', 'lima', '');
add_bio_pop('Fundulus', 'lineolatus', '');
add_bio_pop('Fundulus', 'luciae', '');
add_bio_pop('Fundulus', 'majalis', '');
add_bio_pop('Fundulus', 'notatus', '');
add_bio_pop('Fundulus', 'nottii', '');
add_bio_pop('Fundulus', 'olivaceus', '');
add_bio_pop('Fundulus', 'parvipinnis', '');
add_bio_pop('Fundulus', 'persimilis', '');
add_bio_pop('Fundulus', 'pulvereus', '');
add_bio_pop('Fundulus', 'rathbuni', '');
add_bio_pop('Fundulus', 'relictus', '');
add_bio_pop('Fundulus', 'rubrifons', '');
add_bio_pop('Fundulus', 'sciadicus', '');
add_bio_pop('Fundulus', 'seminolis', '');
add_bio_pop('Fundulus', 'similis', '');
add_bio_pop('Fundulus', 'stellifer', '');
add_bio_pop('Fundulus', 'waccamensis', '');
add_bio_pop('Fundulus', 'zebrinus', '');
add_bio_pop('Garmanella', 'pulchra', '');
add_bio_pop('Gnatholebias', 'hoignei', '');
add_bio_pop('Gnatholebias', 'hoignei', 'Finca BBL 01-06');
add_bio_pop('Gnatholebias', 'hoignei', 'PapelóBL 01-03');
add_bio_pop('Gnatholebias', 'zonatus', '');
add_bio_pop('Gnatholebias', 'zonatus', 'Apure BBL 01-05');
add_bio_pop('Gnatholebias', 'zonatus', 'Finca BBL 01-06');
add_bio_pop('Hylopanchax', 'stictopleuron', '');
add_bio_pop('Hypsopanchax', 'catenatus', '');
add_bio_pop('Hypsopanchax', 'jobaerti', '');
add_bio_pop('Hypsopanchax', 'jubbi', '');
add_bio_pop('Hypsopanchax', 'modestus', '');
add_bio_pop('Hypsopanchax', 'platysternus', '');
add_bio_pop('Hypsopanchax', 'zebra', '');
add_bio_pop('Jordanella', 'floridae', '');
add_bio_pop('Laciris', 'pelagica', '');
add_bio_pop('Lacustricola', 'atripinna', '');
add_bio_pop('Lacustricola', 'bukobanus', '');
add_bio_pop('Lacustricola', 'bukobanus', 'Karungu KE 01-1');
add_bio_pop('Lacustricola', 'camerunensis', '');
add_bio_pop('Lacustricola', 'centralis', '');
add_bio_pop('Lacustricola', 'hutereaui', '');
add_bio_pop('Lacustricola', 'jeanneli', '');
add_bio_pop('Lacustricola', 'johnstoni', '');
add_bio_pop('Lacustricola', 'kassenjiensis', '');
add_bio_pop('Lacustricola', 'katangae', '');
add_bio_pop('Lacustricola', 'kongoraensis', '');
add_bio_pop('Lacustricola', 'kongoraensis', 'Kikale 02-10');
add_bio_pop('Lacustricola', 'kongoraensis', 'Kilimani TAN 02-15');
add_bio_pop('Lacustricola', 'kongoraensis', 'Luhule River TAN 02-8');
add_bio_pop('Lacustricola', 'kongoraensis', 'Ruhoi River TAN 02-13');
add_bio_pop('Lacustricola', 'kongoraensis', 'Rungungu TAN 02-11');
add_bio_pop('Lacustricola', 'kongoranensis', '');
add_bio_pop('Lacustricola', 'kongoranensis', 'Iragua TAN 00-16');
add_bio_pop('Lacustricola', 'kongoranensis', 'Jaribu TAN 00-21');
add_bio_pop('Lacustricola', 'kongoranensis', 'Kiparanganda TAN 00-24.');
add_bio_pop('Lacustricola', 'kongoranensis', 'Lupiro TAN 00-15');
add_bio_pop('Lacustricola', 'kongoranensis', 'Mbezi River TAN 00-23');
add_bio_pop('Lacustricola', 'kongoranensis', 'Minepa TAN 00-14');
add_bio_pop('Lacustricola', 'kongoranensis', 'Ruvu River TAN 00-17');
add_bio_pop('Lacustricola', 'kongoranensis', 'TZL 46-01');
add_bio_pop('Lacustricola', 'kongoranesis', '');
add_bio_pop('Lacustricola', 'lacustris', '');
add_bio_pop('Lacustricola', 'lualabaensis', '');
add_bio_pop('Lacustricola', 'macrurus', '');
add_bio_pop('Lacustricola', 'maculatus-lacustris', '');
add_bio_pop('Lacustricola', 'maculatus-lacustris', 'Jaribu TAN 00-21');
add_bio_pop('Lacustricola', 'maculatus-lacustris', 'Lupiro TAN 00-15');
add_bio_pop('Lacustricola', 'maculatus-lacustris', 'Ruvu River TAN 00-17');
add_bio_pop('Lacustricola', 'matthesi', '');
add_bio_pop('Lacustricola', 'mediolateralis', '');
add_bio_pop('Lacustricola', 'moeruensis', '');
add_bio_pop('Lacustricola', 'myaposae', '');
add_bio_pop('Lacustricola', 'nigrolateralis', '');
add_bio_pop('Lacustricola', 'omoculatus', '');
add_bio_pop('Lacustricola', 'pumilis', '');
add_bio_pop('Lacustricola', 'usanguensis', '');
add_bio_pop('Lacustricola', 'vitschumbaensis', '');
add_bio_pop('Lamprichthys', 'tanganicanus', '');
add_bio_pop('Leptolebias', 'aureoguttatus', '');
add_bio_pop('Leptolebias', 'aureoguttatus', 'ItanhaéRDB 01-02.');
add_bio_pop('Leptolebias', 'cruzi', '');
add_bio_pop('Leptolebias', 'leitaoi', '');
add_bio_pop('Leptolebias', 'marmoratus', '');
add_bio_pop('Leptolebias', 'minimus', '');
add_bio_pop('Leptolebias', 'opalescens', '');
add_bio_pop('Leptolebias', 'splendens', '');
add_bio_pop('Leptolucania', 'ommata', '');
add_bio_pop('Lucania', 'goodei', '');
add_bio_pop('Lucania', 'interioris', '');
add_bio_pop('Lucania', 'parva', '');
add_bio_pop('Maratecoara', 'formosa', '');
add_bio_pop('Maratecoara', 'lacortei', '');
add_bio_pop('Megalebias', 'cheradophilus', '');
add_bio_pop('Megalebias', 'elongatus', '');
add_bio_pop('Megalebias', 'monstrosus', '');
add_bio_pop('Megalebias', 'prognathus', '');
add_bio_pop('Megalebias', 'schreitmuelleri', '');
add_bio_pop('Megalebias', 'wolterstorffi', '');
add_bio_pop('Megupsilon', 'aporus', '');
add_bio_pop('Micromoema', 'xiphophora', '');
add_bio_pop('Micropanchax', 'antinorii', '');
add_bio_pop('Micropanchax', 'bracheti', '');
add_bio_pop('Micropanchax', 'ehrichi', '');
add_bio_pop('Micropanchax', 'fuelleborni', '');
add_bio_pop('Micropanchax', 'fuelleborni', 'Duma River TAN 00-6');
add_bio_pop('Micropanchax', 'keilhacki', '');
add_bio_pop('Micropanchax', 'kingii', '');
add_bio_pop('Micropanchax', 'loati', '');
add_bio_pop('Micropanchax', 'pfaffi', '');
add_bio_pop('Micropanchax', 'rudolfianus', '');
add_bio_pop('Millerichthys', 'robustus', '');
add_bio_pop('Moema', 'pepotei', '');
add_bio_pop('Moema', 'piriana', '');
add_bio_pop('Moema', 'portugali', '');
add_bio_pop('Moema', 'staecki', '');
add_bio_pop('Nematolebias', 'myersi', '');
add_bio_pop('Nematolebias', 'whitei', '');
add_bio_pop('Neofundulus', 'acutirostratus', '');
add_bio_pop('Neofundulus', 'guaporensis', '');
add_bio_pop('Neofundulus', 'ornatipinnis', '');
add_bio_pop('Neofundulus', 'paraguayensis', '');
add_bio_pop('Neofundulus', 'parvipinnis', '');
add_bio_pop('Nothobranchius', 'albimarginatus', '');
add_bio_pop('Nothobranchius', 'albimarginatus', 'Kiparanganda TAN 00-24');
add_bio_pop('Nothobranchius', 'albimarginatus', 'Kiparanganda TAN 02-33.');
add_bio_pop('Nothobranchius', 'albimarginatus', 'Kitonga TZL 55-01');
add_bio_pop('Nothobranchius', 'albimarginatus', 'Mbezi River TAN 00-23');
add_bio_pop('Nothobranchius', 'annectens', '');
add_bio_pop('Nothobranchius', 'annectens', 'Bagamoyo TAN 02-29');
add_bio_pop('Nothobranchius', 'annectens', 'Kikale TAN 92-10');
add_bio_pop('Nothobranchius', 'annectens', 'Rufiji River Camp TAN 02-18');
add_bio_pop('Nothobranchius', 'annectens', 'Ruhoi River TAN 02-13');
add_bio_pop('Nothobranchius', 'annectens', 'Ruvu River TAN 00-20');
add_bio_pop('Nothobranchius', 'annectens', 'Ruvu River TAN 02-30');
add_bio_pop('Nothobranchius', 'annectens', 'Ruvu River TAN 02-31');
add_bio_pop('Nothobranchius', 'annectens', 'TZL 49-01');
add_bio_pop('Nothobranchius', 'annectens', 'TZL 51-01');
add_bio_pop('Nothobranchius', 'annectens', 'TZL-01-01');
add_bio_pop('Nothobranchius', 'bojiensis', '');
add_bio_pop('Nothobranchius', 'brieni', '');
add_bio_pop('Nothobranchius', 'eggersi', '');
add_bio_pop('Nothobranchius', 'eggersi', 'Bagamoyo 02-28');
add_bio_pop('Nothobranchius', 'eggersi', 'Bagamoyo 02-29');
add_bio_pop('Nothobranchius', 'eggersi', 'Bagamoyo TZL 52-01');
add_bio_pop('Nothobranchius', 'eggersi', 'Kilimani TAN 02-15');
add_bio_pop('Nothobranchius', 'eggersi', 'Rufiji River Camp 02-17');
add_bio_pop('Nothobranchius', 'eggersi', 'Rufiji River Camp 02-20 (red phenotype)');
add_bio_pop('Nothobranchius', 'eggersi', 'Rufiji River Camp TAN 02-16 (red phenotype)');
add_bio_pop('Nothobranchius', 'eggersi', 'Ruhoi River TAN 02-12');
add_bio_pop('Nothobranchius', 'eggersi', 'Ruvu River TAN 00-20');
add_bio_pop('Nothobranchius', 'elongatus', '');
add_bio_pop('Nothobranchius', 'elongatus', 'Dida KE 01-9,');
add_bio_pop('Nothobranchius', 'elongatus', 'Kinago KE 01-13');
add_bio_pop('Nothobranchius', 'elongatus', 'Mariakani KE 01-14.');
add_bio_pop('Nothobranchius', 'fasciatus', '');
add_bio_pop('Nothobranchius', 'flammicomantis', '');
add_bio_pop('Nothobranchius', 'flammicomantis', 'TZL 47-01');
add_bio_pop('Nothobranchius', 'foerschi', '');
add_bio_pop('Nothobranchius', 'foerschi', 'Soga TAN 02-27');
add_bio_pop('Nothobranchius', 'foerschi', 'TZL 49-01');
add_bio_pop('Nothobranchius', 'furzeri', '');
add_bio_pop('Nothobranchius', 'furzeri', 'Mazimechopes River MOZ 04-13');
add_bio_pop('Nothobranchius', 'furzeri', 'Mazimechopes River MZ 04-2');
add_bio_pop('Nothobranchius', 'furzeri', 'Mazimechopes River MZ 04-3');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-10');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-11');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-14');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-16');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-3');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-6');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-7');
add_bio_pop('Nothobranchius', 'furzeri', 'MZM 04-8');
add_bio_pop('Nothobranchius', 'fuscotaeniatus', '');
add_bio_pop('Nothobranchius', 'gemius', '');
add_bio_pop('Nothobranchius', 'gemius', 'TAN Narbungo TAN 02-24');
add_bio_pop('Nothobranchius', 'guentheri', '');
add_bio_pop('Nothobranchius', 'interruptus', '');
add_bio_pop('Nothobranchius', 'interruptus', 'Kikambala KE 01-10');
add_bio_pop('Nothobranchius', 'janpapi', '');
add_bio_pop('Nothobranchius', 'janpapi', 'Bagamoyo TAN 02-28');
add_bio_pop('Nothobranchius', 'janpapi', 'Dutumi TAN 02-21');
add_bio_pop('Nothobranchius', 'janpapi', 'Kikale TAN 02-10');
add_bio_pop('Nothobranchius', 'janpapi', 'Kilimani TAN 02-15');
add_bio_pop('Nothobranchius', 'janpapi', 'Lazaba TAN 00-18');
add_bio_pop('Nothobranchius', 'janpapi', 'Ndundu TAN 00-22');
add_bio_pop('Nothobranchius', 'janpapi', 'Rufiji River Camp TAN 02-16');
add_bio_pop('Nothobranchius', 'janpapi', 'Rufiji River Camp TAN 02-17');
add_bio_pop('Nothobranchius', 'janpapi', 'Rufiji River Camp TAN 02-18');
add_bio_pop('Nothobranchius', 'janpapi', 'Rufiji River Camp TAN 02-19');
add_bio_pop('Nothobranchius', 'janpapi', 'Rufiji River Camp TAN 02-20');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruhoi River TAN 02 -13');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruhoi River TAN 02-12');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruvu River TAN 00-19');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruvu River TAN 00-20');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruvu River TAN 02-30');
add_bio_pop('Nothobranchius', 'janpapi', 'Ruvu RiverTAN 02-31');
add_bio_pop('Nothobranchius', 'janpapi', 'Soga TAN 02-27');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL 01-01');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL 02-01');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL 47-01');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL 50-01');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL 52-01');
add_bio_pop('Nothobranchius', 'janpapi', 'TZL TZL 49-01');
add_bio_pop('Nothobranchius', 'jubbi', '');
add_bio_pop('Nothobranchius', 'jubbi', 'Marereni KE 01-6');
add_bio_pop('Nothobranchius', 'jubbi', 'Marereni KE 01-7');
add_bio_pop('Nothobranchius', 'jubbi', 'Sabaki River KE 01-5');
add_bio_pop('Nothobranchius', 'jubbi', 'Sabaki River KE 01-8');
add_bio_pop('Nothobranchius', 'kafuensis', '');
add_bio_pop('Nothobranchius', 'kilombaroensis', '');
add_bio_pop('Nothobranchius', 'kilombaroensis', 'Ideete TAN 02-23');
add_bio_pop('Nothobranchius', 'kilombaroensis', 'Idete TAN 02-22');
add_bio_pop('Nothobranchius', 'kilombaroensis', 'Ifakara TAN 02-26');
add_bio_pop('Nothobranchius', 'kilombaroensis', 'Narubungo TAN 02-24');
add_bio_pop('Nothobranchius', 'kirki', '');
add_bio_pop('Nothobranchius', 'korthausae', '');
add_bio_pop('Nothobranchius', 'korthausae', 'Kwachepa');
add_bio_pop('Nothobranchius', 'korthausae', 'Luhule River TAN 02-8');
add_bio_pop('Nothobranchius', 'korthausae', 'Mafia Island TAN 02-1');
add_bio_pop('Nothobranchius', 'korthausae', 'Mafia Island TAN 02-2');
add_bio_pop('Nothobranchius', 'korthausae', 'Mafia Island TAN 02-3');
add_bio_pop('Nothobranchius', 'korthausae', 'Mafia Island TAN 02-5');
add_bio_pop('Nothobranchius', 'korthausae', 'Mbezi River TAN 00-23');
add_bio_pop('Nothobranchius', 'korthausae', 'Mbezi River TAN 02-32');
add_bio_pop('Nothobranchius', 'korthausae', 'Mbezi River TAN 02-6');
add_bio_pop('Nothobranchius', 'korthausae', 'Rungungu TAN 02-11');
add_bio_pop('Nothobranchius', 'korthausae', 'Sotele TAN 02-7');
add_bio_pop('Nothobranchius', 'lourensi', '');
add_bio_pop('Nothobranchius', 'lourensi', 'Ifakara 02-26');
add_bio_pop('Nothobranchius', 'lourensi', 'Ifakara TAN 00-13');
add_bio_pop('Nothobranchius', 'lourensi', 'Ihanga TAN 02-25');
add_bio_pop('Nothobranchius', 'lourensi', 'Lupiro TAN 00-15');
add_bio_pop('Nothobranchius', 'lourensi', 'Minepa TAN 00-14');
add_bio_pop('Nothobranchius', 'lourensi', 'Narubungo TAN 02-24');
add_bio_pop('Nothobranchius', 'luekei', '');
add_bio_pop('Nothobranchius', 'luekei', 'Kiparanganda TAN 02-33');
add_bio_pop('Nothobranchius', 'luekei', 'Luhule River TAN 02-8');
add_bio_pop('Nothobranchius', 'luekei', 'Mbezi River TAN 00-23');
add_bio_pop('Nothobranchius', 'luekei', 'Mbezi River TAN 02-32');
add_bio_pop('Nothobranchius', 'malaissei', '');
add_bio_pop('Nothobranchius', 'melanospilus', '');
add_bio_pop('Nothobranchius', 'melanospilus', 'Bagamoyo TAN 02-29');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ihanga TAN 02-25');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kikale TAN 02-9');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kilale TAN02-10');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kilimani TAN 02-15');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kimamba TAN 00-12');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kiparanganda TAN 00-24');
add_bio_pop('Nothobranchius', 'melanospilus', 'Kiparanganda TAN 02-33');
add_bio_pop('Nothobranchius', 'melanospilus', 'Lazaba TAN 00-18');
add_bio_pop('Nothobranchius', 'melanospilus', 'Luhule River TAN 02-8');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mafia Island TAN 02-4');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mafia Island TAN 02-5');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mbezi River TAN 00-23');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mbezi River TAN 02-6');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mbezi TAN 02-32');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mkongo TAN 02-14');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mvuha TZL 44-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'Mvumi TAN 00-11');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ndundu TAN 00-22');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ramisi KE 01-11');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ramisi KE 01-12');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-16');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-17');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-18');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-19');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-20');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rufiji River Camp TAN 02-21');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruhoi TAN 02-12');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruhoi TAN 02-13');
add_bio_pop('Nothobranchius', 'melanospilus', 'Rungungu TAN 02-11');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruvu River TAN 00-19');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruvu River TAN 00-20');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruvu River TAN 02-30');
add_bio_pop('Nothobranchius', 'melanospilus', 'Ruvu River TAN 02-31');
add_bio_pop('Nothobranchius', 'melanospilus', 'Soga TAN 02-27');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 01-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 02-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 03-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 04-01)');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 05-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 06-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 07-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 08-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 09-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 10-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 12-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 13-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 14-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 15-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 45-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 46-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 47-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 49-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 50-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 51-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 52-01');
add_bio_pop('Nothobranchius', 'melanospilus', 'TZL 55-01');
add_bio_pop('Nothobranchius', 'microlepis', '');
add_bio_pop('Nothobranchius', 'mkuziensis', '');
add_bio_pop('Nothobranchius', 'neumanni', '');
add_bio_pop('Nothobranchius', 'neumanni', 'Bahi TAN 00-10');
add_bio_pop('Nothobranchius', 'neumanni', 'Manyara TZL 22-01');
add_bio_pop('Nothobranchius', 'neumanni', 'Ndabaka Gate TAN 00-4');
add_bio_pop('Nothobranchius', 'neumanni', 'Salali TZL 23-01');
add_bio_pop('Nothobranchius', 'neumanni', 'Tarime River TAN 00-3');
add_bio_pop('Nothobranchius', 'neumanni', 'TZL 18-01');
add_bio_pop('Nothobranchius', 'neumanni', 'TZL 19-01');
add_bio_pop('Nothobranchius', 'neumanni', 'TZL 24-01');
add_bio_pop('Nothobranchius', 'ocellatus', '');
add_bio_pop('Nothobranchius', 'ocellatus', 'Kilimani TAN 02-15');
add_bio_pop('Nothobranchius', 'ocellatus', 'Lazaba TAN 00-18');
add_bio_pop('Nothobranchius', 'ocellatus', 'Ruhoi River 02-13');
add_bio_pop('Nothobranchius', 'ocellatus', 'Ruvu 02-31');
add_bio_pop('Nothobranchius', 'ocellatus', 'Ruvu River TAN 00-20');
add_bio_pop('Nothobranchius', 'orthonotus', '');
add_bio_pop('Nothobranchius', 'orthonotus', 'Beira MOZ 04-3');
add_bio_pop('Nothobranchius', 'orthonotus', 'Dondo MOZ 04-6');
add_bio_pop('Nothobranchius', 'orthonotus', 'Gorongose River MOZ 04-2');
add_bio_pop('Nothobranchius', 'orthonotus', 'Lima River MOZ 04-8');
add_bio_pop('Nothobranchius', 'orthonotus', 'Mazimechopes River MOZ 04-13');
add_bio_pop('Nothobranchius', 'orthonotus', 'Mazimechopes River MZ 04-1');
add_bio_pop('Nothobranchius', 'orthonotus', 'Mazimechopes River MZ 04-2');
add_bio_pop('Nothobranchius', 'orthonotus', 'Mazimechopes River MZ 04-3');
add_bio_pop('Nothobranchius', 'orthonotus', 'Muda River MOZ 04-5');
add_bio_pop('Nothobranchius', 'orthonotus', 'MZM 04-10');
add_bio_pop('Nothobranchius', 'orthonotus', 'MZM 04-12');
add_bio_pop('Nothobranchius', 'orthonotus', 'MZM 04-13');
add_bio_pop('Nothobranchius', 'orthonotus', 'MZM 04-16');
add_bio_pop('Nothobranchius', 'orthonotus', 'MZM 04-3');
add_bio_pop('Nothobranchius', 'orthonotus', 'Nicuadala MOZ 04-10');
add_bio_pop('Nothobranchius', 'orthonotus', 'Quelimane MOZ 04-9');
add_bio_pop('Nothobranchius', 'orthonotus', 'Rio Savene MOC 01-1');
add_bio_pop('Nothobranchius', 'orthonotus', 'Save River MOZ 04-1');
add_bio_pop('Nothobranchius', 'orthonotus', 'Zangue River MOZ 04-7');
add_bio_pop('Nothobranchius', 'palmqvisti', '');
add_bio_pop('Nothobranchius', 'palmqvisti', 'Ramisi KE 01-11');
add_bio_pop('Nothobranchius', 'palmqvisti', 'Ramisi KE 01-12');
add_bio_pop('Nothobranchius', 'patrizii', '');
add_bio_pop('Nothobranchius', 'patrizii', 'Marereni KE 01-06');
add_bio_pop('Nothobranchius', 'polli', '');
add_bio_pop('Nothobranchius', 'rachovii', '');
add_bio_pop('Nothobranchius', 'rachovii', 'Beira MOZ 04-3');
add_bio_pop('Nothobranchius', 'rachovii', 'Dondo MOZ 04-6');
add_bio_pop('Nothobranchius', 'rachovii', 'Gorongose River MOZ 04-2');
add_bio_pop('Nothobranchius', 'rachovii', 'Lima River MOZ 04-8');
add_bio_pop('Nothobranchius', 'rachovii', 'Mazimechopes River MOZ 04-13');
add_bio_pop('Nothobranchius', 'rachovii', 'Mazimechopes River MZ 04-1');
add_bio_pop('Nothobranchius', 'rachovii', 'Mazimechopes River MZ 04-2');
add_bio_pop('Nothobranchius', 'rachovii', 'Mazimechopes River MZ 04-3');
add_bio_pop('Nothobranchius', 'rachovii', 'Muda River MOZ 04-5');
add_bio_pop('Nothobranchius', 'rachovii', 'MZM 04-12');
add_bio_pop('Nothobranchius', 'rachovii', 'MZM 04-13');
add_bio_pop('Nothobranchius', 'rachovii', 'MZM 04-3');
add_bio_pop('Nothobranchius', 'rachovii', 'MZM 04-6');
add_bio_pop('Nothobranchius', 'rachovii', 'MZM 04-7');
add_bio_pop('Nothobranchius', 'rachovii', 'Nicuadala MOZ 04-10');
add_bio_pop('Nothobranchius', 'rachovii', 'Quelimane MOZ 04-9');
add_bio_pop('Nothobranchius', 'rachovii', 'Rio Savane MOC 01-1');
add_bio_pop('Nothobranchius', 'robustus', '');
add_bio_pop('Nothobranchius', 'robustus', 'Sio River KE 01-4');
add_bio_pop('Nothobranchius', 'rubripinnis', '');
add_bio_pop('Nothobranchius', 'rubripinnis', 'Kitonga TZL 54-01');
add_bio_pop('Nothobranchius', 'rubripinnis', 'Luhule River TAN 02-8');
add_bio_pop('Nothobranchius', 'rubripinnis', 'Mbezi River TAN 00-23');
add_bio_pop('Nothobranchius', 'rubripinnis', 'Mbezi River TAN 02-32');
add_bio_pop('Nothobranchius', 'rubripinnis', 'Mbezi TAN 02-6');
add_bio_pop('Nothobranchius', 'rubroreticulatus', '');
add_bio_pop('Nothobranchius', 'sp.', '');
add_bio_pop('Nothobranchius', 'sp.', 'aff. korthausae Kwachepa TZL 53-01');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Ifakara TAN 00-13');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Ifakara TAN 02-26');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Iragua TAN 00-16');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Lupiro TAN 00-15');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Minepa TAN 00-14');
add_bio_pop('Nothobranchius', 'sp.', 'aff. melanospilus Narubungo TAN 02-25');
add_bio_pop('Nothobranchius', 'sp.', 'aff. taeniopygus TZL 20-01');
add_bio_pop('Nothobranchius', 'sp.', 'Bujora Nyashigwe TZL 26-01');
add_bio_pop('Nothobranchius', 'sp.', 'Caprivi NA 01-1');
add_bio_pop('Nothobranchius', 'sp.', 'Iragua TAN 00-16');
add_bio_pop('Nothobranchius', 'sp.', 'Kasanka ZAM 00-1');
add_bio_pop('Nothobranchius', 'sp.', 'Kilombero Iragua TAN 00-16');
add_bio_pop('Nothobranchius', 'sp.', 'Kilombero Lupiro TAN 00-15');
add_bio_pop('Nothobranchius', 'sp.', 'Kilombero Minepa TAN 00-14');
add_bio_pop('Nothobranchius', 'sp.', 'Kilombero .Singelele. TZL 46-0');
add_bio_pop('Nothobranchius', 'sp.', 'Lupiro TAN 00-15');
add_bio_pop('Nothobranchius', 'sp.', 'Mabuki TAN 00-7');
add_bio_pop('Nothobranchius', 'sp.', 'Makonde Melela River MOZ 04-11');
add_bio_pop('Nothobranchius', 'sp.', 'Makonde Molocue River MOZ 04-12');
add_bio_pop('Nothobranchius', 'sp.', 'Motukeri TAN 00-1');
add_bio_pop('Nothobranchius', 'sp.', 'Nata TAN 00-2');
add_bio_pop('Nothobranchius', 'sp.', 'Nyando River KE 01-2');
add_bio_pop('Nothobranchius', 'sp.', 'Nyando River KE 01-3');
add_bio_pop('Nothobranchius', 'sp.', 'Runere TZL 27-01');
add_bio_pop('Nothobranchius', 'sp.', 'Tarime River TAN 00-3');
add_bio_pop('Nothobranchius', 'steinforti', '');
add_bio_pop('Nothobranchius', 'symoensi', '');
add_bio_pop('Nothobranchius', 'taeniopygus', '');
add_bio_pop('Nothobranchius', 'taeniopygus', 'Kibitilwa TZL 29-01');
add_bio_pop('Nothobranchius', 'taeniopygus', 'Manonga River TAN 00-8');
add_bio_pop('Nothobranchius', 'taeniopygus', 'Masanza Kona TZL 25-01');
add_bio_pop('Nothobranchius', 'taeniopygus', 'TZL 28-01');
add_bio_pop('Nothobranchius', 'taeniopygus', 'TZL 34-01');
add_bio_pop('Nothobranchius', 'taeniopygus', 'Wembere River TAN 00-9');
add_bio_pop('Nothobranchius', 'ugandensis', '');
add_bio_pop('Nothobranchius', 'ugandensis', 'Sio River KE 01-4');
add_bio_pop('Nothobranchius', 'virgatus', '');
add_bio_pop('Nothobranchius', 'vosseleri', '');
add_bio_pop('Nothobranchius', 'willerti', '');
add_bio_pop('Orestias', 'agassizii', '');
add_bio_pop('Orestias', 'crawfordi', '');
add_bio_pop('Orestias', 'ctenolepis', '');
add_bio_pop('Orestias', 'cuvieri', '');
add_bio_pop('Orestias', 'elegans', '');
add_bio_pop('Orestias', 'forgeti', '');
add_bio_pop('Orestias', 'gilsoni', '');
add_bio_pop('Orestias', 'gracilis', '');
add_bio_pop('Orestias', 'gymnotus', '');
add_bio_pop('Orestias', 'hardini', '');
add_bio_pop('Orestias', 'imarpe', '');
add_bio_pop('Orestias', 'incae', '');
add_bio_pop('Orestias', 'ispi', '');
add_bio_pop('Orestias', 'jussiei', '');
add_bio_pop('Orestias', 'luteus', '');
add_bio_pop('Orestias', 'minimus', '');
add_bio_pop('Orestias', 'minutus', '');
add_bio_pop('Orestias', 'mooni', '');
add_bio_pop('Orestias', 'mulleri', '');
add_bio_pop('Orestias', 'multiporis', '');
add_bio_pop('Orestias', 'mundus', '');
add_bio_pop('Orestias', 'olivaceus', '');
add_bio_pop('Orestias', 'pentlandii', '');
add_bio_pop('Orestias', 'polonorum', '');
add_bio_pop('Orestias', 'puni', '');
add_bio_pop('Orestias', 'richersoni', '');
add_bio_pop('Orestias', 'robustus', '');
add_bio_pop('Orestias', 'silustani', '');
add_bio_pop('Orestias', 'taquiri', '');
add_bio_pop('Orestias', 'tchernavini', '');
add_bio_pop('Orestias', 'tomcooni', '');
add_bio_pop('Orestias', 'tschudii', '');
add_bio_pop('Orestias', 'tutini', '');
add_bio_pop('Orestias', 'uruni', '');
add_bio_pop('Orestias', 'ututo', '');
add_bio_pop('Oxyzygonectes', 'dovii', '');
add_bio_pop('Pachypanchax', 'nuchimaculatus', '');
add_bio_pop('Pachypanchax', 'omalonotus', '');
add_bio_pop('Pachypanchax', 'playfairii', '');
add_bio_pop('Pachypanchax', 'sakaramyi', '');
add_bio_pop('Pantanodon', 'madagascariensis', '');
add_bio_pop('Pantanodon', 'stuhlmanni', '');
add_bio_pop('Papiliolebias', 'bitteri', '');
add_bio_pop('Pituna', 'compacta', '');
add_bio_pop('Plataplocheilus', 'cabindae', '');
add_bio_pop('Plataplocheilus', 'cabindae', 'BBW 00-2');
add_bio_pop('Plataplocheilus', 'cabindae', 'BBW 00-3');
add_bio_pop('Plataplocheilus', 'ngaensis', '');
add_bio_pop('Plataplocheilus', 'ngaensis', 'BBW 00-25.');
add_bio_pop('Plataplocheilus', 'sp.', '');
add_bio_pop('Plataplocheilus', 'sp.', 'aff. cabindae BBW 00-22');
add_bio_pop('Plataplocheilus', 'sp.', 'aff. cabindae BBW 00-23');
add_bio_pop('Plataplocheilus', 'sp.', 'BBW 00-1');
add_bio_pop('Plataplocheilus', 'sp.', 'BBW 00-24');
add_bio_pop('Plataplochilus', 'cabindae', '');
add_bio_pop('Plataplochilus', 'cabindae', 'GJS 00-22 Douengui');
add_bio_pop('Plataplochilus', 'loemensis', '');
add_bio_pop('Plataplochilus', 'miltotaenia', '');
add_bio_pop('Plataplochilus', 'ngaensis', '');
add_bio_pop('Plataplochilus', 'terveri', '');
add_bio_pop('Platapochilus', 'ngaensis', '');
add_bio_pop('Platapochilus', 'ngaensis', 'Bicomo GEMLB 02-32.');
add_bio_pop('Plesiolebias', 'aruana', '');
add_bio_pop('Plesiolebias', 'glaucopterus', '');
add_bio_pop('Plesiolebias', 'lacerdai', '');
add_bio_pop('Plesiolebias', 'xaventei', '');
add_bio_pop('Poropanchax', 'brichardi', '');
add_bio_pop('Poropanchax', 'luxophthalmus hannerzi', '');
add_bio_pop('Poropanchax', 'luxophthalmus luxophthalmus', '');
add_bio_pop('Poropanchax', 'myersi', '');
add_bio_pop('Poropanchax', 'normani', '');
add_bio_pop('Poropanchax', 'rancureli', '');
add_bio_pop('Poropanchax', 'scheeli', '');
add_bio_pop('Poropanchax', 'scheeli', 'Rui Ue GAMLB 02-28');
add_bio_pop('Procatopus', 'aberrans', '');
add_bio_pop('Procatopus', 'nototaenia', '');
add_bio_pop('Procatopus', 'similis', '');
add_bio_pop('Procatopus', 'similis', 'GEMHS 00-43');
add_bio_pop('Procatopus', 'similis', 'Nsupu GEMHS 00-42');
add_bio_pop('Procatopus', 'sp.', '');
add_bio_pop('Procatopus', 'sp.', 'Bicomo GEML 00-15');
add_bio_pop('Profundulus', 'candalarius', '');
add_bio_pop('Profundulus', 'guatemalensis', '');
add_bio_pop('Profundulus', 'hildebrandi', '');
add_bio_pop('Profundulus', 'labialis', '');
add_bio_pop('Profundulus', 'punctatus', '');
add_bio_pop('Pronothobranchius', 'kiyawensis', '');
add_bio_pop('Pterolebias', 'bokermanni', '');
add_bio_pop('Pterolebias', 'bokermanni', 'Guaicurus RDB 02-03');
add_bio_pop('Pterolebias', 'longipinnis', '');
add_bio_pop('Pterolebias', 'phasianus', '');
add_bio_pop('Pterolebias', 'phasianus', 'Guaicurus RDB 02-04.');
add_bio_pop('Rachovia', 'brevis', '');
add_bio_pop('Rachovia', 'brevis', 'Carrasquero BBL 01-01 (5 km north of Centro Don Bo');
add_bio_pop('Rachovia', 'hummelincki', '');
add_bio_pop('Rachovia', 'maculipinnis', '');
add_bio_pop('Rachovia', 'maculipinnis', 'Ca?o Delgadito BBL 01-04');
add_bio_pop('Rachovia', 'maculipinnis', 'Finca BBL 01-06');
add_bio_pop('Rachovia', 'maculipinnis', 'PapelóBL 01-03');
add_bio_pop('Rachovia', 'pyropunctata', '');
add_bio_pop('Rachovia', 'pyropunctata', 'Bachaquero BBL 01-02');
add_bio_pop('Rachovia', 'pyropunctata', 'Carrasquero BBL 01-01 (5 km north of Centro Don Bo');
add_bio_pop('Rachovia', 'stellifer', '');
add_bio_pop('Renova', 'oscari', '');
add_bio_pop('Rhexipanchax', 'kabae', '');
add_bio_pop('Rhexipanchax', 'lamberti', '');
add_bio_pop('Rhexipanchax', 'nimbaensis', '');
add_bio_pop('Rhexipanchax', 'schioetzi', '');
add_bio_pop('Rivulus', 'agilae', '');
add_bio_pop('Rivulus', 'altivelis', '');
add_bio_pop('Rivulus', 'amphoreus', '');
add_bio_pop('Rivulus', 'atratus', '');
add_bio_pop('Rivulus', 'bahianus', '');
add_bio_pop('Rivulus', 'beniensis beniensis', '');
add_bio_pop('Rivulus', 'beniensis lacustris', '');
add_bio_pop('Rivulus', 'birkhahni', '');
add_bio_pop('Rivulus', 'boehlkei', '');
add_bio_pop('Rivulus', 'bolivianus', '');
add_bio_pop('Rivulus', 'brasiliensis', '');
add_bio_pop('Rivulus', 'breviceps', '');
add_bio_pop('Rivulus', 'brunneus', '');
add_bio_pop('Rivulus', 'campelloi', '');
add_bio_pop('Rivulus', 'caudomarginatus', '');
add_bio_pop('Rivulus', 'christinae', '');
add_bio_pop('Rivulus', 'chucunaque chucunaque', '');
add_bio_pop('Rivulus', 'chucunaque sucubti', '');
add_bio_pop('Rivulus', 'cladophorus', '');
add_bio_pop('Rivulus', 'compressus', '');
add_bio_pop('Rivulus', 'corpulentus', '');
add_bio_pop('Rivulus', 'cryptocallus', '');
add_bio_pop('Rivulus', 'cylindraceus', '');
add_bio_pop('Rivulus', 'decoratus', '');
add_bio_pop('Rivulus', 'deltaphilus', '');
add_bio_pop('Rivulus', 'depressus', '');
add_bio_pop('Rivulus', 'derhami', '');
add_bio_pop('Rivulus', 'elegans', '');
add_bio_pop('Rivulus', 'elongatus', '');
add_bio_pop('Rivulus', 'erberi', '');
add_bio_pop('Rivulus', 'frenatus', '');
add_bio_pop('Rivulus', 'frommi', '');
add_bio_pop('Rivulus', 'fuscolineatus', '');
add_bio_pop('Rivulus', 'geayi', '');
add_bio_pop('Rivulus', 'glaucus', '');
add_bio_pop('Rivulus', 'gransabanae', '');
add_bio_pop('Rivulus', 'haraldsiolii', '');
add_bio_pop('Rivulus', 'hartii', '');
add_bio_pop('Rivulus', 'hildebrandi', '');
add_bio_pop('Rivulus', 'holmiae', '');
add_bio_pop('Rivulus', 'igneus', '');
add_bio_pop('Rivulus', 'immaculatus', '');
add_bio_pop('Rivulus', 'insulaepinorum', '');
add_bio_pop('Rivulus', 'intermittens', '');
add_bio_pop('Rivulus', 'iridescens', '');
add_bio_pop('Rivulus', 'isthmensis', '');
add_bio_pop('Rivulus', 'janeiroensis', '');
add_bio_pop('Rivulus', 'jucundus', '');
add_bio_pop('Rivulus', 'kuelpmanni', '');
add_bio_pop('Rivulus', 'lanceolatus', '');
add_bio_pop('Rivulus', 'leucurus', '');
add_bio_pop('Rivulus', 'limoncochae', '');
add_bio_pop('Rivulus', 'luelingi', '');
add_bio_pop('Rivulus', 'lungi', '');
add_bio_pop('Rivulus', 'lyricauda', '');
add_bio_pop('Rivulus', 'magdalenae', '');
add_bio_pop('Rivulus', 'marmoratus', '');
add_bio_pop('Rivulus', 'mazaruni', '');
add_bio_pop('Rivulus', 'micropus', '');
add_bio_pop('Rivulus', 'modestus', '');
add_bio_pop('Rivulus', 'monikae', '');
add_bio_pop('Rivulus', 'monticola', '');
add_bio_pop('Rivulus', 'montium', '');
add_bio_pop('Rivulus', 'nicoi', '');
add_bio_pop('Rivulus', 'nudiventris', '');
add_bio_pop('Rivulus', 'obscurus', '');
add_bio_pop('Rivulus', 'ophiomimus', '');
add_bio_pop('Rivulus', 'ornatus', '');
add_bio_pop('Rivulus', 'pacificus', '');
add_bio_pop('Rivulus', 'peruanus', '');
add_bio_pop('Rivulus', 'pictus', '');
add_bio_pop('Rivulus', 'pictus', 'Costa Rica RDB 01-01');
add_bio_pop('Rivulus', 'punctatus', '');
add_bio_pop('Rivulus', 'rectocaudatus', '');
add_bio_pop('Rivulus', 'roloffi', '');
add_bio_pop('Rivulus', 'rubripunctatus', '');
add_bio_pop('Rivulus', 'rubrolineatus', '');
add_bio_pop('Rivulus', 'santensis', '');
add_bio_pop('Rivulus', 'speciosus', '');
add_bio_pop('Rivulus', 'stagnatus', '');
add_bio_pop('Rivulus', 'stellifer', '');
add_bio_pop('Rivulus', 'stellifer', 'Finca BBL 01-06');
add_bio_pop('Rivulus', 'taeniatus', '');
add_bio_pop('Rivulus', 'tenius', '');
add_bio_pop('Rivulus', 'tenuis', '');
add_bio_pop('Rivulus', 'tenuis', 'GUAPP 1-2001 Chiminos, Rio Petexbatum');
add_bio_pop('Rivulus', 'tenuis', 'GUAPP 2-2001 Las Marí');
add_bio_pop('Rivulus', 'tessellatus', '');
add_bio_pop('Rivulus', 'uroflammeus siegfriedi', '');
add_bio_pop('Rivulus', 'uroflammeus uroflammeus', '');
add_bio_pop('Rivulus', 'urophthalmus', '');
add_bio_pop('Rivulus', 'villwocki', '');
add_bio_pop('Rivulus', 'violaceus', '');
add_bio_pop('Rivulus', 'waimacui', '');
add_bio_pop('Rivulus', 'wassmanni', '');
add_bio_pop('Rivulus', 'weberi', '');
add_bio_pop('Rivulus', 'xanthonotus', '');
add_bio_pop('Rivulus', 'xiphidius', '');
add_bio_pop('Rivulus', 'zygonectes', '');
add_bio_pop('Scriptaphyosemion', 'bertholdi', '');
add_bio_pop('Scriptaphyosemion', 'brueningi', '');
add_bio_pop('Scriptaphyosemion', 'cauveti', '');
add_bio_pop('Scriptaphyosemion', 'chaytori', '');
add_bio_pop('Scriptaphyosemion', 'chaytori', 'Ngabu CI 03/02');
add_bio_pop('Scriptaphyosemion', 'etzeli', '');
add_bio_pop('Scriptaphyosemion', 'geryi', '');
add_bio_pop('Scriptaphyosemion', 'guignardi', '');
add_bio_pop('Scriptaphyosemion', 'liberiense', '');
add_bio_pop('Scriptaphyosemion', 'roloffi', '');
add_bio_pop('Scriptaphyosemion', 'schmitti', '');
add_bio_pop('Simpsonichthys', 'alternatus', '');
add_bio_pop('Simpsonichthys', 'boitonei', '');
add_bio_pop('Simpsonichthys', 'bokermanni', '');
add_bio_pop('Simpsonichthys', 'chacoensis', '');
add_bio_pop('Simpsonichthys', 'constanciae', '');
add_bio_pop('Simpsonichthys', 'costai', '');
add_bio_pop('Simpsonichthys', 'filamentosus', '');
add_bio_pop('Simpsonichthys', 'flammeus', '');
add_bio_pop('Simpsonichthys', 'flavicaudatus', '');
add_bio_pop('Simpsonichthys', 'fulminantis', '');
add_bio_pop('Simpsonichthys', 'ghisolfii', '');
add_bio_pop('Simpsonichthys', 'hellneri', '');
add_bio_pop('Simpsonichthys', 'heloplites', '');
add_bio_pop('Simpsonichthys', 'magnificus', '');
add_bio_pop('Simpsonichthys', 'marginatus', '');
add_bio_pop('Simpsonichthys', 'multiradiatus', '');
add_bio_pop('Simpsonichthys', 'notatus', '');
add_bio_pop('Simpsonichthys', 'santanae', '');
add_bio_pop('Simpsonichthys', 'similis', '');
add_bio_pop('Simpsonichthys', 'stellatus', '');
add_bio_pop('Simpsonichthys', 'trilineatus', '');
add_bio_pop('Simpsonichthys', 'zonatus', '');
add_bio_pop('Spectrolebias', 'semiocellatus', '');
add_bio_pop('Stenolebias', 'bellus', '');
add_bio_pop('Stenolebias', 'damascenoi', '');
add_bio_pop('Terranatos', 'dolichopterus', '');
add_bio_pop('Tomeurus', 'gracilis', '');
add_bio_pop('Trigonectes', 'aplocheiloides', '');
add_bio_pop('Trigonectes', 'balzanii', '');
add_bio_pop('Trigonectes', 'balzanni', '');
add_bio_pop('Trigonectes', 'balzanni', 'Curva do Leque RDB 02-04');
add_bio_pop('Trigonectes', 'balzanni', 'Guaicurus RDB 02-03');
add_bio_pop('Trigonectes', 'balzanni', 'Miranda RDB 02-02');
add_bio_pop('Trigonectes', 'macrophthalmus', '');
add_bio_pop('Trigonectes', 'rogoaguae', '');
add_bio_pop('Trigonectes', 'rubromarginatus', '');
add_bio_pop('Trigonectes', 'strigabundus', '');
add_bio_pop('Valencia', 'hispanica', '');
add_bio_pop('Valencia', 'letourneuxi', '');
add_bio_pop('_Artwork', 'Clothing', '');
add_bio_pop('_Artwork', 'Other', '');
add_bio_pop('_Artwork', 'Prints', '');
add_bio_pop('_Food', 'Brine Shrimp', '');
add_bio_pop('_Food', 'Dwarf African Red Worms', '');
add_bio_pop('_Food', 'Fruit Flies', '');
add_bio_pop('_Food', 'Grindal Worms', '');
add_bio_pop('_Food', 'Microworms', '');
add_bio_pop('_Food', 'Other', '');
add_bio_pop('_Food', 'Vinegar Eels', '');
add_bio_pop('_Food', 'White Worms', '');
add_bio_pop('_Plants', 'Floating', '');
add_bio_pop('_Plants', 'Other', '');
add_bio_pop('_Plants', 'Pond', '');
add_bio_pop('_Plants', 'Rooted', '');
add_bio_pop('_Print Materials', 'Book', '');
add_bio_pop('_Print Materials', 'Magazine', '');
add_bio_pop('_Print Materials', 'Other', '');
add_bio_pop('_Supplies', 'Bags', '');
add_bio_pop('_Supplies', 'Mops', '');
add_bio_pop('_Supplies', 'Other', '');
add_bio_pop('_Supplies', 'Peat Pellets', '');
